# ワークフロー名
name: test_line_notify

# 発火タイミング
on:
  push:

jobs:
  build:
    # Ubuntuの最新版環境内で処理
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
        # pip更新
          python -m pip install --upgrade pip
        # 必要なパッケージインストール
          pip install -r requirements.txt
      - name: Run script
        run: |
          # main.pyの実行
          python scraping.py
